# Generated by Django 4.1.7 on 2023-02-18 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_pet_breed_account_pet_breeds"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("weight", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="account",
            name="pet_breeds",
        ),
        migrations.DeleteModel(
            name="PetBreed",
        ),
        migrations.AddField(
            model_name="pet",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="accounts.account",
            ),
        ),
    ]
